version: '2'

volumes:
  wayland-socket:
  tailscale:

services:
  server:
    build: ./server
    network_mode: host

  kiosk:
    build: ./kiosk
    network_mode: host
    depends_on:
      - weston
      - server
    devices:
      - /dev/dri/renderD128
    volumes:
      - 'wayland-socket:/run/shm/wayland'

  weston:
    build: ./weston
    network_mode: none
    privileged: true
    volumes:
      - 'wayland-socket:/run/shm/wayland'

  networking:
    build: ./networking
    network_mode: host
    privileged: true
    volumes:
      - tailscale:/tailscale
